lib/API/DX/Device.cpp

There's no need to split the workload into multiple command-lists, and there are various unnecessary waitForSignal's that can be removed.
Also fixed logic for deciding if a resource is a UAV or not (UAV's are ReadWrite, not ReadOnly resources).

D3D12: Remove unnecessary waits and command list executions

---

lib/API/DX/Device.cpp

- we only need the ID3D12Debug1 debug interface
- no need to hold on to the factory / debug interfaces
- no need to track devices once they've been registered
Once all that's gone there's nothing really left for DirectXContext to do.

Simplify InitializeDXDevices

---

test/Basic/StructuredBuffer-packed.test

This moves the current structured buffer test to a new file and introduces a simpler one that doesn't need llvm/llvm-project#104503 and llvm/llvm-project#121010 to be in place in order to pass.
Note: this would be better if it exercised both SRVs and UAVs, but SRV support isn't implemented in the test framework yet.

Introduce a simpler StructuredBuffer test

---

.github/workflows/macos-clang-mtl.yaml
.github/workflows/windows-intel-clang-d3d12.yaml
.github/workflows/windows-intel-clang-warp-d3d12.yaml
.github/workflows/windows-nv-clang-d3d12.yaml
.github/workflows/windows-nv-clang-vk.yaml
.github/workflows/windows-nv-dxc-d3d12.yaml
.github/workflows/windows-nv-dxc-vk.yaml
test/Basic/StructuredBuffer.test

This PR adds the currently passing clang build configurations to the PR checks, and marks the StructuredBuffer test as unsupoorted on Clang because it is currently crashing Clang.

Enable passing clang builders for prs

---

.github/workflows/test-all.yaml
include/Image/Color.h
include/Image/Image.h
include/Image/ImageComparators.h
lib/Image/CMakeLists.txt
lib/Image/Image.cpp
lib/Image/ImageComparators.cpp
test/Basic/Mandelbrot.test
test/CMakeLists.txt
test/lit.cfg.py
tools/CMakeLists.txt
tools/imgdiff/CMakeLists.txt
tools/imgdiff/imgdiff.cpp
tools/offloader/offloader.cpp

This change introduces a new image diff tool that has two modes for comparing PNG images.
The "Exact Match" mode loads a PNG and compares the decoded image data. This comensates for differences in the image generation tool, image headers or other encoding differences.
The "CIE76" mode compares the two images computing the CIE76 color difference, and fails if the difference of the worst pixel is greater than 2.3, which corresponds to a "just noticeable" difference. Additionally, when using the CIE match mode, a rules file may be specified with the `-rules` option to allow customizing the failure conditions based on furthest color distance, root mean square of the whole image, root mean square of the noticeably different pixels, percentage of pixels with differences, or percentage-based …

Add new imagediff tool

---

lib/Image/Color.cpp

Some failures are occuring due to floating point precision where very small negative values are sticking around through XYZ->RGB transformation. This Should correct for that by clamping the RGB values.

Clamp RGB values between 0 and 1

---

test/Basic/StructuredBuffer.test

As of llvm/llvm-project#121725 structured buffer is fully supported in clang.

Mark clang as supported for StructuredBuffer test

---

lib/API/DX/Device.cpp
lib/API/MTL/MTLDevice.cpp
test/Basic/StructuredBuffer.test

This is mostly cargo-culting the logic from UAVs and adjusting for the simpler read-only case of SRVs.
Note that I don't have a setup locally for Vulkan right now, so I've just XFAIL'd the test in Vulkan configs for now.

Support for SRVs

---

lib/API/VK/Device.cpp
test/Basic/StructuredBuffer-SRV.test
test/Basic/StructuredBuffer.test
test/lit.cfg.py

Vulkan doesn't have the same division between SRV and UAV that DirectX does, so this refactors the buffer handling code to merge SRVs and UAVs. We will need different handling for other types of buffers in the future (i.e. CBVs which map to uniform buffers), but for now this gets pairity between DX and VK.
The SRV test for structured buffers that @bogner added in his last PR miscompiles to DXC SPIR-V, so this PR adds a new test to handle more basic StructuredBuffer SRV use.

Add StructuredBuffer SRV Test

---

lib/API/DX/Device.cpp
lib/API/MTL/MTLDevice.cpp
lib/API/VK/Device.cpp
test/Basic/cbuffer.test

This adds support for cbuffer declarations to the HLSL test suite.
In DirectX, cbuffer declarations map in as Constant Buffer Views (CBV).
In Vulkan, cbuffer declarations map in as uniform buffers.
In Metal, they're just a read-only raw buffer.
There may be some nuances around data layout in constant buffers that aren't consistent between the three platforms so the included test case is extremely simple while we figure out what works and what doesn't.

Add support for cbuffer resource bindings

---

include/Image/Image.h
include/Support/Pipeline.h
lib/API/DX/Device.cpp
lib/API/MTL/MTLDevice.cpp
lib/API/VK/Device.cpp
lib/Support/Pipeline.cpp
test/Basic/DescriptorSets.test
test/Basic/Mandelbrot.test
test/Basic/StructuredBuffer-SRV.test
test/Basic/StructuredBuffer-packed.test
test/Basic/StructuredBuffer.test
test/Basic/TestFloat32Pipeline.test
test/Basic/TestPipeline.test
test/Basic/cbuffer.test
test/Basic/idiv-edges.test
test/Basic/simple.test
test/WaveOps/WaveActiveMax.test
test/WaveOps/WaveActiveSum.test
tools/offloader/offloader.cpp

This change separates the definition of buffers of data from the resource bindings that connect them to shaders.
I believe this is a simplification that will make it easier to write tests because we'll have user-defined names that we can match on in the output.

Refactor defining buffers to use named buffers

---

include/API/Device.h
include/Support/Pipeline.h
lib/API/DX/Device.cpp
lib/API/MTL/MTLDevice.cpp
lib/API/VK/Device.cpp
lib/Support/Pipeline.cpp
test/Basic/DescriptorSets.test
test/Basic/Mandelbrot.test
test/Basic/StructuredBuffer-SRV.test
test/Basic/StructuredBuffer-packed.test
test/Basic/StructuredBuffer.test
test/Basic/TestFloat32Pipeline.test
test/Basic/TestPipeline.test
test/Basic/cbuffer.test
test/Basic/idiv-edges.test
test/Basic/simple.test
test/WaveOps/WaveActiveMax.test
test/WaveOps/WaveActiveSum.test
tools/offloader/offloader.cpp

This update alters the YAML representation to capture the shader stage and entry function names. Previously I had hacked in `main` in a few places and we surprisingly haven't tripped over it.
I've updated the `TestPipeline` test to use `CSMain` to verify that we can actually change the entry point's name and have everything still work.

Support shader stages in YAML

---

test/Basic/DescriptorSets.test
test/Basic/Mandelbrot.test
test/Basic/StructuredBuffer-SRV.test
test/Basic/StructuredBuffer-packed.test
test/Basic/StructuredBuffer.test
test/Basic/TestFloat32Pipeline.test
test/Basic/TestPipeline.test
test/Basic/cbuffer.test
test/Basic/idiv-edges.test
test/Basic/simple.test
test/WaveOps/WaveActiveMax.test
test/WaveOps/WaveActiveSum.test
test/lit.cfg.py

This replaces the `dxc` tool invocation with `%dxc_target` which includes the target-specific options (i.e. `-spirv`) so that we can simplify our RUN lines.
We still need special handling for Metal to convert dxil to metal libraries... for now.

[NFC] Add a `%dxc_target` substitution

---

test/Basic/DescriptorSets.test
test/Basic/Mandelbrot.test
test/Basic/StructuredBuffer-SRV.test
test/Basic/StructuredBuffer-packed.test
test/Basic/StructuredBuffer.test
test/Basic/TestFloat32Pipeline.test
test/Basic/TestPipeline.test
test/Basic/cbuffer.test
test/Basic/idiv-edges.test
test/Basic/simple.test
test/WaveOps/WaveActiveMax.test
test/WaveOps/WaveActiveSum.test
test/lit.cfg.py

This adapts the test suite to use the clang and DXC `-metal` flag when running the tests. This significantly simplifies the run lines, but requires bleeding edge DXC and Clang.

Simplify Metal test runs

---

lib/API/CMakeLists.txt
lib/API/DX/Device.cpp
test/M3/RootSignatures/DescriptorTables.test
test/M3/RootSignatures/TwoDescriptorTables.test
test/M3/RootSignatures/lit.local.cfg

This updates the DX device code to inspect the shader for a precompiled root signature and use that instead of building a root signature from scratch.
Still missing support for root descriptors, root constants and lots of tests, but this is a good starting base.

[DX] Use the root signature from a shader if present

---

test/M3/RootSignatures/Defaults.test
test/M3/RootSignatures/Flags.test
test/M3/RootSignatures/ManualDescriptors.test
test/M3/RootSignatures/NumberParameters.test
test/M3/RootSignatures/ParameterInsensitivity.test

adds testing demonstrating the various behaviours of specifying a root signature through a function attribute in HLSL for non-sampler descriptor types
- `Defaults.test`: all default parameter values
- `Flags.test`: various root/descriptor flags for M3
- `NumberParameters.test`: integer parameter edge-cases
- `ManualDescriptors.test`: shows manual user specified `offset` and `numDescriptors` parameters and the edge-cases
- `ParameterInsensitivity.test`: shows that parameters have no specified order, as well as, the case-insensitivity of keywords and enums
Noted discrepancies with the [root signature specification](https://github.com/llvm/wg-hlsl/blob/main/proposals/0002-root-signature-in-clang.md) are tracked to be resolved here: https://github.com/llvm/wg-hlsl/issues/192. 
Resolves: …

[RootSignature] Add frontend RootSignature testing

---

test/M3/RootSignatures/NumberParameters.test

- The register spaces 0xfffffff0 to 0xffffffff are reserved, the original testcase is meant to demonstrate that we can use the valid value of 0xfffffff0 - 1 = 0xffffffef = 4294967279, which it does
- However, the comment describing the testcase specifies the wrong value
This commit resolves the discrepancy by fixing up the comment typo as noted here: https://github.com/llvm-beanz/offload-test-suite/pull/45#discussion_r2017664530

[NFC] Fix typo in NumberParameters test description

---

lib/API/DX/Device.cpp

If the D3D debug layer detects a problem it will error out of the program. Print any messages it had logged to its info queue for debugging purposes.

Print D3D debug messages on signal

---

test/Feature/CBuffer/structs.test

The layout and packing rules for constant variables in DirectX is quite weird. The official docs can be found [here](https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-packing-rules). There's also a handy visualization tool [here](https://maraneshi.github.io/HLSL-ConstantBufferLayoutVisualizer/).

Add test for structures in cbuffers

---

test/Basic/DescriptorSets.test
test/Basic/TestPipeline.test
test/Basic/simple.test

Clang supports RWBuffer for Vulkan now, so these tests should pass!

[VK] Enable RWBuffer tests in Clang

---

test/Feature/CBuffer/arrays-16bit.test
test/Feature/CBuffer/arrays-64bit.test
test/Feature/CBuffer/arrays.test
test/Feature/CBuffer/vectors-16bit.test
test/Feature/CBuffer/vectors.test

- Avoid implicit bindings.
- Disable tests that do array casts for now.

Update CBuffer tests to work with clang

---

include/Support/Pipeline.h
lib/API/DX/Device.cpp
test/Feature/RawBuffers/ByteAddressBuffers.test

Adds test and support for `ByteAddressBuffer` and `RWByteAddressBuffer` (DirectX only).
Fixes llvm/wg-hlsl#201

Add support and tests for `ByteAddressBuffer` for DirectX

---

include/Support/Pipeline.h
lib/Support/Pipeline.cpp

Add Bool to DataFormat Enum, represent it with a uint32_t because HLSL bools are 4 bytes and a C++ bool is 1 byte.
This will be needed for future intrinsic tests.
Closes #73

Add Bool as a Scalar type option

---

README.md

@spall encountered this issue while setting up the offload test suite on Windows.
The offload test suite uses the DirectX debug layer by default and therefore fails to run correctly when the Graphics Tools optional feature is not installed.
Without Graphics Tools, the error `failed to create D3D12 Debug Interface` will prevent api-query and the offloader from running properly.

[NFC] Add Graphics Tools to prerequisites for Windows

---

test/Feature/ImplicitBindings/all-implicit.test

This test doesn't populate BufC correctly on metal.

Mark implicit bindings test as unsupported on metal

---

include/Support/Pipeline.h
lib/Support/Pipeline.cpp

Add Float16 to DataFormat Enum, represented with a uint16_t.
This will be needed for future intrinsic tests.
Closes #79.

Add Float16 as a Scalar type option

---

.github/workflows/macos-clang-mtl.yaml
.github/workflows/macos-dxc-mtl.yaml
.github/workflows/windows-intel-clang-d3d12.yaml
.github/workflows/windows-intel-clang-vk.yaml
.github/workflows/windows-intel-clang-warp-d3d12.yaml
.github/workflows/windows-intel-dxc-d3d12.yaml
.github/workflows/windows-intel-dxc-vk.yaml
.github/workflows/windows-intel-dxc-warp-d3d12.yaml
.github/workflows/windows-nv-clang-d3d12.yaml
.github/workflows/windows-nv-clang-vk.yaml
.github/workflows/windows-nv-dxc-d3d12.yaml
.github/workflows/windows-nv-dxc-vk.yaml

This uses a fallback option so that it will pull the pull_request head SHA if that value is available, otherwise it will fall back to the github ref value.

Update action target to use PR head

---

README.md
lib/Support/Check.cpp
lib/Support/Pipeline.cpp
test/Tools/Offloader/BufferFuzzy-16bit.test
test/Tools/Offloader/BufferFuzzy-error-16bit.test

- Add the `compareFloat16ULP` function to do ULP Comparison for Float16 ([reference](https://github.com/microsoft/DirectXShaderCompiler/blob/624665f3987d379a299aa14dbc53e0cd3b96afea/include/dxc/Test/HlslTestUtils.h#L567))
- Update `BufferFuzzy` to support Float16 and call the new function to compare Float16 values
- Add tests to show `BufferFuzzy` testing valid and invalid cases
Closes #81.

Add ULP comparison support for Float16

---

.github/workflows/windows-intel-clang-d3d12.yaml
.github/workflows/windows-intel-clang-vk.yaml
.github/workflows/windows-intel-clang-warp-d3d12.yaml
.github/workflows/windows-intel-dxc-vk.yaml
.github/workflows/windows-intel-dxc-warp-d3d12.yaml

The intel builder is a single machine building 6 configurations... It just can't keep up. This reduces the scheduled builds to every 2 hours to help it stay on top of PRs.

Reduce intel builder schedule

---

.github/workflows/pr-code-format.yml

The workflow was pointed at my username because that's where the repo was originally, now it should point at LLVM.

Fix the code-format workflow

---

.clang-format
.clang-tidy
.github/workflows/windows-intel-clang-d3d12.yaml
.github/workflows/windows-intel-clang-vk.yaml
.github/workflows/windows-intel-clang-warp-d3d12.yaml
CMakeLists.txt
README.md
docs/WSL.md
include/API/Device.h
lib/API/DX/Device.cpp
lib/API/Device.cpp
lib/API/MTL/MTLDevice.cpp
lib/API/VK/Device.cpp
lib/Image/Color.cpp
lib/Image/Image.cpp
lib/Image/ImageComparators.cpp
lib/Support/Check.cpp
lib/Support/Pipeline.cpp
tools/api-query/api-query.cpp
tools/imgdiff/imgdiff.cpp
tools/offloader/offloader.cpp
unittests/Image/ColorTests.cpp

This PR configures clang-tidy to enforce a swath of rules that comply with and enforce LLVM's coding standards.
Two new CMake options are added:
* `OFFLOADTEST_USE_CLANG_TIDY` - When set to `On` this runs clang-tidy on non-third-party sources in the offload-test-suite as part of the build process.
* `OFFLOADTEST_CLANG_TIDY_APPLY_FIX` - When set to `On` passes `--fix` to `clang-tidy` to automatically apply fix-its for any issues that have fixes available (Requires `OFFLOADTEST_USE_CLANG_TIDY=On`).
The enabled warning set is:
`clang-diagnostic-*` - Clang compiler diagnostics.
`llvm-*` - LLVM coding standards
`misc-*` - All miscellaneous rules except:
* [misc-use-anonymous-namespace](https://clang.llvm.org/extra/clang-tidy/checks/misc/use-anonymous-namespace.html), which violates LLVM coding …

[NFC] Apply clang-tidy

---

test/Basic/TestFloat32Pipeline.test
test/Basic/TestPipeline.test
test/Basic/idiv-edges.test
test/Basic/simple.test
test/Feature/HLSLLib/length.test
test/Feature/HLSLLib/saturate.test
test/Feature/StructuredBuffer/layout.test
test/Feature/StructuredBuffer/srv.test
test/Feature/StructuredBuffer/stride.test
test/Tools/Offloader/BufferExact-error.test
test/Tools/Offloader/BufferExact.test
test/Tools/Offloader/BufferFuzzy-error.test
test/Tools/Offloader/BufferFuzzy.test
test/UseCase/particle-life.test
test/WaveOps/WaveActiveMax.test

This removes `UNSUPPORTED: Clang-Vulkan` from most of then tests that had it. These tests pass with top-of-tree LLVM.
There are a couple of places we need to keep unsupported tests for now:
- Tests that use -fvk-use-scalar-layout flag
- Tests that use the vk::binding attribute

Enable most of the vulkan tests under clang

---

lib/Support/Check.cpp

`std::fpclassify`, `std::isnan`, and `std::signbit` were depended on in a previous PR. These are defined in `<cmath>` but it wasn't included.  By happenstance that is okay on windows but breaks the linux build.
My best guess is that `cmath` is included indirectly on the windows platform but not linux.

[WSL] Fix building under WSL

---

test/Feature/HLSLLib/or.test

Add test for or function
Closes #128

add test for or

---

test/Feature/ImplicitBindings/all-implicit.test
test/Feature/ImplicitBindings/simple-resources.test

Enables implicit resource binding tests for Clang-DXC.
Depends on llvm/llvm-project#142061.

Enable implicit binding tests for Clang-DXC

---

test/Feature/HLSLLib/dot4add.test

We test `dot4add_i8packed` and `dot4add_u8packed` on the same inputs, showing the difference in signed vs unsigned results.
Fixes #123 and #149.

Add tests for the dot4add functions

---

lib/API/VK/Device.cpp

A first vkCreateInstance is called to enumerate devices and immediately destroyed. The resulting handle is not reset to VK_NULL_HANDLE. This means if the second vkCreateInstance fails (missing layer for ex), the dtor will call vkDestroyInstance with an already freed instance, causing a crash.

[VK] Fix crash if validation layers are absent

---

test/Feature/HLSLLib/countbits.16.test
test/Feature/HLSLLib/countbits.32.test
test/Feature/HLSLLib/countbits.64.test

Implement tests for `countbits` intrinsic with `uint16_t`, `int16_t`, `uint`, `uint32_t`, `int64_t` and `uint64_t`.
Resolves https://github.com/llvm/offload-test-suite/issues/140

Implement tests for `countbits`

---

README.md
lib/API/VK/Device.cpp

Set pEnabledFeatures and pNext in VkDeviceCreateInfo
See: https://registry.khronos.org/vulkan/specs/latest/man/html/VkDeviceCreateInfo.html
Closes #220

set enabledFeatures when creating vulkan device

---

test/Feature/HLSLLib/ldexp.16.test
test/Feature/HLSLLib/ldexp.32.test

Change `BufferFuzzy` to `BufferFloatULP` after #217 was merged in. Fixes failing `ldexp` tests.

Fix `ldexp` tests

---

test/Feature/CBuffer/arrays-64bit.test
test/lit.cfg.py

Previously this code was creating a merged feature set for WARP and the available device. This instead only configures the features for the native device when not using WARP, and only configures WARPs features when you are using WARP.

Fix handling of device features for DX

---

test/Feature/HLSLLib/isinf.16.test
test/lit.cfg.py

The Metal Shader Converter 3 beta released today fixes this test. This change marks it as unsupported on Metal with older versions of the shader converter.

Enable isinf.16.test with metal shader converter 3

---

lib/API/VK/Device.cpp

If the device fails to be created and the error is not recorginzied, the
error message impossible to act on. If we output the error number, then
the user can look it up, and see what needs to be done.

Print the VK error code

---

test/CMakeLists.txt

This fixes generation of the sub-directory targets for the generated nested lit executions.

[CMake] Fix generation of lit subdirectory targets

---

test/lit.cfg.py

Int64 support in Metal goes way back at least covering the full range of macOS hardware in active support.

[Metal] Enable Int64 tests on Metal.

---

test/lit.cfg.py

Use a raw string for the regex to avoid warnings about `\.` being treated as an escape sequence, and use an f-string for string interpolation as is the modern python style.

Clean up strings in shaderconverter version check. NFC

---

.github/workflows/build-and-test-callable.yaml
docs/WSL.md
test/Feature/CBuffer/lit.local.cfg
test/UseCase/particle-life.test

When moving to LLVM I clearly missed a few places where my personal repo was originally referenced. This gets the last of them.

Cleanup references to the original repo on my personal GitHub

---

include/Support/Pipeline.h
lib/Support/Check.cpp
lib/Support/Pipeline.cpp

This PR changes a member variable name to prevent compiler errors when compiling with g++-11.
Instead of using -fpermissive, this PR changes the conflicting member variable name.
Fixes https://github.com/llvm/offload-test-suite/issues/281

Use `ComparisonRule` to prevent ambiguity between type and member variable name

---

include/Support/Pipeline.h
lib/Support/Check.cpp
lib/Support/Pipeline.cpp
test/Tools/Offloader/BufferExact-error.test
test/Tools/Offloader/BufferFloat-error-64bit.test

This PR implements some extra quality of life to address confusion in seemingly identical actual and expected results.
Fixes https://github.com/llvm/offload-test-suite/issues/289
Here's some sample output of what I see when I force a test to fail, manually changing expected values.

Add comparison rule, tolerance if applicable, and hex64 view to test failure text output

---

test/Feature/StructuredBuffer/dec_counter.test
test/Feature/StructuredBuffer/inc_counter.test

plus change `UNSUPPORTED:` to `XFAIL:` for Vulkan and Metal and add links to issues.

Enable structured buffer counter tests for Clang

---

test/Feature/ResourceArrays/array-local.test
test/Feature/ResourceArrays/array-local2.test
test/Feature/ResourceArrays/multi-dim-array-global.test
test/Feature/ResourceArrays/multi-dim-array-local.test
test/Feature/ResourceArrays/multi-dim-array-subset.test
test/Feature/ResourceArrays/multi-dim-unbounded-array.test
test/Feature/ResourceArrays/unbounded-array.test

Add tests for arrays of resources to the offload test suite, including arrays declared locally or used as function arguments, multi-dimensional arrays, or subsets of multi-dimensional arrays. One test for global arrays was already added in #302 when support for resource arrays was added to the offload test suite.
Closes llvm/wg-hlsl#292

Add tests for resource arrays

---

test/Feature/HLSLLib/reversebits.16.test
test/Feature/HLSLLib/reversebits.32.test
test/Feature/HLSLLib/reversebits.64.test

Closes #135.
Adds tests for `reversebits` testing `UInt16`, `UInt32`, `UInt64` types. Some values for 16 bit and 32 bit pulled from [HLK tests](https://github.com/microsoft/DirectXShaderCompiler/blob/57177f77a4dc6996400ac97a0d618799c82374e8/tools/clang/unittests/HLSLExec/ShaderOpArithTable.xml#L2647), but those tested signed ints so ended up not really being the same. No HLK test for 64 bit.
Need to remove XFAILs after [#7680](https://github.com/microsoft/DirectXShaderCompiler/issues/7680) and [#152049](https://github.com/llvm/llvm-project/issues/152049) are fixed.

Add `reversebits` tests

---

lib/API/VK/Device.cpp

Some linux distros still only have the Vulkan 1.3 SDK readily available - this allows folks using those to run these tests without jumping through too many hoops.

Conditionalize dependency on the Vulkan 1.4 SDK

---

test/Feature/HLSLLib/dot.32.test
test/Feature/HLSLLib/dot.fp16.test
test/Feature/HLSLLib/dot.fp64.test
test/Feature/HLSLLib/dot.int16.test
test/Feature/HLSLLib/dot.int64.test

Closes #124.
Adds tests for `dot` testing 16 bit int types, half, 32 bit types, 64 bit int types, and double (only supports scalar double not vector). Didn't use the [HLK test inputs](https://github.com/microsoft/DirectXShaderCompiler/blob/57177f77a4dc6996400ac97a0d618799c82374e8/tools/clang/unittests/HLSLExec/ShaderOpArithTable.xml#L4766) because it was testing 9 inputs for each of vector sizes 2-4, and the tests were mostly for nans, infs, and denorms.

Add `dot` tests

---

test/Feature/HLSLLib/asint16.fp16.test
test/Feature/HLSLLib/asint16.int16.test

Add tests for asint16 with input types uint16_t, int16_t, and half.
Closes #173

Add tests for asint16

---

test/Feature/HLSLLib/asuint16.fp16.test
test/Feature/HLSLLib/asuint16.int16.test

Add test for asuint16 for half, uint16_t and int16_t.
Closes #179

add test for asuint16

---

test/Feature/HLSLLib/asint.test

Adds a test for asint testing int, uint, and float types.
Closes #169

add test for asint

---

test/Feature/HLSLLib/cosh.32.test
test/Feature/HLSLLib/sinh.16.test
test/Feature/HLSLLib/sinh.32.test
test/Feature/HLSLLib/tanh.16.test
test/Feature/HLSLLib/tanh.32.test

Unlike the standard trig functions which may be implemented as natural calculations or as hyperbolic aproximations, the hyperbolic functions are guaranteed to be hyperbolc aproximations and thus have consistent precision characteristics.
These can all be guaranteed within 2 ULP, which gives a better match and will resolve the test failures on AMD GPUs.
The `cosh.16` test is not updated in this PR because it is already using ULP rules and 2 ULP range specification.
I've captured a spec issue to follow up on the very wide range requirements for `tanh` on NVIDIA GPUs:
https://github.com/microsoft/hlsl-specs/issues/601
This issue has also been observed by WGSL and is reflected in their spec:
https://github.com/gpuweb/gpuweb/pull/5199
Fixes #326

Adjust hyperbolic trig functions to use ULP rules

---

test/Feature/HLSLLib/fmod.16.test
test/Feature/HLSLLib/fmod.32.test

Add test for half and float versions of fmod.
closes #172

add test for fmod

---

test/Feature/HLSLLib/cross.16.test
test/Feature/HLSLLib/cross.32.test

Closes #159. 
Adds tests for `cross` testing `half3` and `float3` (it only accepts vectors of length 3). 
Still had to use `half4` and `float4` for the buffers because of alignment issues.

Add `cross` tests

---

test/Feature/HLSLLib/all.32.test
test/Feature/HLSLLib/all.bool.test
test/Feature/HLSLLib/all.fp16.test
test/Feature/HLSLLib/all.fp64.test
test/Feature/HLSLLib/all.int16.test
test/Feature/HLSLLib/all.int64.test

Closes #111.
Adds tests for `all` testing 16 bit int types, half, 32 bit types, 64 bit int types, and double.
I moved the bool tests from `all.32.test` to a separate file because [this bug](https://github.com/llvm/llvm-project/issues/140824) is causing the vec1 test to fail on Clang, and I didn't want to XFAIL the rest of the 32 bit tests over it. We can combine them in the future once the bug is fixed.

Add `all` tests

---

test/Feature/HLSLLib/asint.test

Tracking the fix in https://github.com/llvm/llvm-project/issues/154214

Add XFAIL for Clang crash

---

test/WaveOps/WaveReadLaneAt.index.test

This PR removes an XFAIL that is passing on our actions now.

Remove XFAIL from failing test

---

test/Feature/WaveOps/WaveActiveAnyTrue.test
test/Feature/WaveOps/WaveActiveCountBits.test

These tests are now passing, so we can remove the XFAIL annotations.

[VK] Remove XFAIL from passing tests

---

test/Feature/HLSLLib/lerp.16.test
test/Feature/HLSLLib/lerp.32.test

Closes #134.
Adds tests for `lerp` testing `half` and `float`.

Add `lerp` tests

---

test/CMakeLists.txt
test/Feature/RootSignatures/Defaults.test
test/Feature/RootSignatures/DescriptorTables.test
test/Feature/RootSignatures/Flags.test
test/Feature/RootSignatures/ManualDescriptors.test
test/Feature/RootSignatures/NumberParameters.test
test/Feature/RootSignatures/ParameterInsensitivity.test
test/Feature/RootSignatures/RootConstants.test
test/Feature/RootSignatures/RootDescriptorAndTables.test
test/Feature/RootSignatures/RootDescriptors.test
test/Feature/RootSignatures/TwoDescriptorTables.test
test/lit.cfg.py

This pr adds testing using `obj2yaml` for root signatures.
There are types of tests added:
- edge-cases: which check for edge cases as specified in the test cases
- consistency: which checks that `DXC` and `clang` set the root signature values to be the same. The particular values are not necessarily important, as they will have been covered in the edge-cases 
Resolves: https://github.com/llvm/offload-test-suite/issues/260.

[RootSignature] Add `obj2yaml` testing

---

include/API/Device.h
lib/API/DX/Device.cpp
lib/API/Device.cpp
lib/API/MTL/MTLDevice.cpp
lib/API/VK/Device.cpp
test/Bugs/Adjacent-Partial-Writes.yaml
test/Bugs/UAV-Sequental-Consistency.yaml
test/CMakeLists.txt
test/lit.cfg.py
test/lit.site.cfg.py.in
tools/api-query/api-query.cpp
tools/offloader/offloader.cpp

This PR adds flags to enable the debug and validation layers for runtimes. Both default to `off` in the offloader tool, but the default CMake configuration enables the debug layer during test suite runs.

Add flags to control debug and validation layers

---

.github/workflows/windows-amd-clang-d3d12.yaml
.github/workflows/windows-amd-clang-vk.yaml
.github/workflows/windows-amd-clang-warp-d3d12.yaml
.github/workflows/windows-amd-dxc-d3d12.yaml
.github/workflows/windows-amd-dxc-vk.yaml
.github/workflows/windows-amd-dxc-warp-d3d12.yaml

Since each build is taking 20-30 minutes, running 6 builds every 2 hours doesn't work. Scaling back to every 6 hours.

Reduce all the AMD scheduled builds to every 6 hours

---

test/Feature/RootSignatures/StaticSamplers.test
test/lit.cfg.py

This pr adds testing for using a `StaticSampler` to describe a `Sampler` resource.
It checks both default and specified parameters are generated correctly.
Resolves https://github.com/llvm/offload-test-suite/issues/261.

[RootSignature] Add `StaticSampler` testing

---

test/Feature/HLSLLib/select.32.test
test/Feature/HLSLLib/select.fp16.test
test/Feature/HLSLLib/select.fp64.test
test/Feature/HLSLLib/select.int16.test
test/Feature/HLSLLib/select.int64.test

Closes #132.
Adds tests for `select` (basic types) testing 16 bit int types, half, 32 bit types, 64 bit int types, and double.
For the `Cond` buffers (and `TrueVal`, `FalseVal` for the bool test), I had to use `bool` instead of `bool4` because select gives an "Invalid overload type" error if it receives a vec1 bool instead of a scalar as input.

Add `select` (basic types) tests

---

test/Basic/matrix_m-based_getter.test
test/Basic/matrix_one-based_getter.test
test/Basic/matrix_scalar_arithmetic.test
test/Basic/matrix_scalar_constructor.test

fixes #457
fixes #458
fixes #459

[matrix] add tests for various matrix frontend features
