.github/workflows/macos-dxc-mtl.yaml
.github/workflows/windows-intel-dxc-d3d12.yaml
.github/workflows/windows-intel-dxc-vk.yaml
.github/workflows/windows-intel-dxc-warp-d3d12.yaml

Add PR merge checks

---

lib/API/DX/Device.cpp

The InfoQueue configuration is set on the device and so it isn't necessary to reconfigure it for each invocation.
As it's part of the device, it is also not necessary to hold on to the InfoQueue interface once we're done with configuring it.

DX: Configure InfoQueue per-device, not per invocation

---

lib/API/DX/Device.cpp

There's an assumption that the resources are created in the same order as they appear in the descriptor heap, which is the order they appear when traversing Pipeline/Sets/Resources. The root signature is where the mapping from index in the descriptor heap to a shader register happens.
Because of this, trying to keep track of the resources via their DX register binding makes things more complicated than necessary, since we can just assume there's a simple mapping of Set/Resource to the resources.

DX: Simplify tracking of resources

---

include/Image/Color.h
lib/Image/Color.cpp
lib/Image/Image.cpp
unittests/Image/ColorTests.cpp

This updates the Image encoder to use the same function for color conversion that will be used elsewhere and is included in the Color header.

[NFC] Refactor and cleanup of color handling

---

include/Image/Image.h
include/Support/Pipeline.h

Clang-format Image.h and remove an unncessary semicolon in Pipeline.h

[NFC] Fix formatting and semicolon

---

test/WaveOps/GSFlag.test

This is based on a discussion around memory models.

Add a test for groupshared flags

---

test/Basic/DescriptorSets.test
test/Basic/TestPipeline.test
test/Basic/simple.test

Reverts llvm-beanz/offload-test-suite#63

Revert "[VK] Enable RWBuffer tests in Clang"

---

test/Feature/StructuredBuffer/layout.test

Demonstrates llvm/llvm-project#121010

Test that structures are packed correctly

---

test/Feature/HLSLLib/length.test

Simple test for the "length" operation

---

test/Feature/HLSLLib/saturate.test

Simple test for the "saturate" operation

---

README.md

Fix spelling of VulkanBinding in the README

---

test/UseCase/particle-life.test

This is a shader that demonstrates that we can compile and run a non-trivial compute shader. It's a slightly modified version of [particle_life.hlsl](https://github.com/damyanp/dplife/blob/main/src/particle_life/particle_life.hlsl)

Add the particle life use case test

---

lib/API/VK/Device.cpp

Initially this code just hard-coded Vulkan 1.1 because you need to set it before you can query device capabilities (which is messy). This changes the code to setup a 1.1 device, query it, then recreate the device with the highest supported version (generally 1.3).
We should update this code to accept a vulkan version from command line arguments (see #189).

[Vulkan] Use the API version from the device

---

test/lit.cfg.py

This just formats the python lit config file to avoid future format violations.

NFC. Format python file to avoid format violations

---

test/Feature/WaveOps/WaveActiveCountBits.test
test/WaveOps/WaveActiveCountBits.test

Test for wave active count bits; Tries to test for divergent control flow and special values of true and false.
Closes #166

Add test for WaveActiveCountBits

---

test/Feature/WaveOps/WaveIsFirstLane.test
test/WaveOps/WaveIsFirstLane.test

Test divergent control flow and usage of WaveIsFirstLane.
Closes #126

Add test for WaveIsFirstLane

---

test/Feature/HLSLLib/cosh.16.test
test/Feature/HLSLLib/cosh.32.test

add 16 and 32 bit float tests for cosh
closes #117

add tests for cosh

---

test/Feature/HLSLLib/trunc.16.test
test/Feature/HLSLLib/trunc.32.test

add 16 and 32 bit float tests for trunc
closes #119

add tests for trunc

---

test/Feature/HLSLLib/asin.16.test
test/Feature/HLSLLib/asin.32.test

add 16 and 32 bit float tests for asin
closes #168

Add tests for asin

---

test/Feature/HLSLLib/log.16.test
test/Feature/HLSLLib/log.32.test

add 16 and 32 bit float tests for log
closes #108

Add test for log

---

test/Feature/HLSLLib/degrees.16.test
test/Feature/HLSLLib/degrees.32.test

Add 16 and 32 bit float tests for degrees
closes #137

Add tests for degrees

---

test/Feature/HLSLLib/radians.16.test
test/Feature/HLSLLib/radians.32.test

add 16 and 32 bit float tests for radians
closes #139

Add test for radians

---

test/Feature/HLSLLib/rsqrt.16.test
test/Feature/HLSLLib/rsqrt.32.test

add 16 and 32 bit float tests for rsqrt
closes #156

add tests for rsqrt

---

test/Feature/HLSLLib/acos.16.test
test/Feature/HLSLLib/acos.32.test

Test for 16 bit and 32 bit acos

test for acos

---

test/Feature/HLSLLib/atan.16.test
test/Feature/HLSLLib/atan.32.test

add 16 and 32 bit float tests for atan
closes #153

add tests for atan

---

test/Feature/HLSLLib/exp2.16.test
test/Feature/HLSLLib/exp2.32.test

add 16 and 32 bit float tests for exp2
closes #136

Add tests for exp2

---

test/Feature/HLSLLib/floor.16.test
test/Feature/HLSLLib/floor.32.test

add 16 and 32 bit float tests for floor
closes #138

add tests for floor

---

test/Feature/HLSLLib/tanh.16.test
test/Feature/HLSLLib/tanh.32.test

add 16 and 32 bit float tests for tanh
closes #145

add tests for tanh

---

lib/API/VK/Device.cpp

This adds extensions as a queryable capability through the device interface for Vulkan. This also gates adding extensions that we had previously been using based on their availabiltiy.
As a last bit, this does include one small line added in the Changes to enable MoltenVK on Apple. When targeting Apple platforms the VK_KHR_PORTABILITY is always enabled. That extension is always required on Apple platforms so we can hard code that one.

Add support for querying extensions

---

test/Feature/HLSLLib/reflect.16.test

This PR just removes some extra conditions on the reflect.16 tests.

Add requires, attempt to remove unsupported

---

.github/workflows/pr-matrix.yaml

This will allow us to opt in to the new nvidia and amd testing configurations as we work through the test failures.

Add the ability to opt-in to testing all hardware configs

---

.github/workflows/windows-amd-dxc-warp-d3d12.yaml
.github/workflows/windows-amd-dxc-warp-preview-d3d12.yaml

This seems to be hanging causing problems on our bots.

Disable WARP preview builder

---

.github/workflows/windows-qc-clang-d3d12.yaml
.github/workflows/windows-qc-clang-vk.yaml
.github/workflows/windows-qc-clang-warp-d3d12.yaml
.github/workflows/windows-qc-dxc-d3d12.yaml
.github/workflows/windows-qc-dxc-vk.yaml
.github/workflows/windows-qc-dxc-warp-d3d12.yaml

Perhaps the last PR (#389) putting these up was too hastily made and reviewed!

Fix the arm64 / Qualcomm workflows so they actually run on arm64 / Qualcomm

---

test/lit.cfg.py

This PR just adds the Qualcomm feature if the device is detected to be Qualcomm via apiquery.

Add Qualcomm feature flag, and some NFCs

---

lib/API/DX/Device.cpp

Move the setting of root signatures to after SetDescriptorHeaps
